# Define common environment variables
x-common-env: &common-env
  - MODEL_TYPE=sgd



services:
  central:
    build:
      context: .
      dockerfile: docker/central/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./central_server:/app
      - ./platform_utils.py:/platform_utils.py
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # GPU access with privileged mode
    privileged: true

  client1:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    environment:
      - CLIENT_ID=client1
      - CENTRAL_SERVER=http://central:8080
      - DATASET_PATH=/data
      - DATA_SOURCE=parquet
      - PARQUET_FILE=/data/dataset.parquet
      - TARGET_COLUMN=label
      - CUDA_VISIBLE_DEVICES=0
      - BATCH_SIZE=2000
      - MAX_ROWS=50000
      - USE_PARTIAL_FIT=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./client:/app
      - ./data/client1:/data
      - ./platform_utils.py:/platform_utils.py
    depends_on:
      - central
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          memory: 160G
        reservations:
          memory: 96G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # GPU access configuration
    privileged: true
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 8gb

  client2:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    environment:
      - CLIENT_ID=client2
      - CENTRAL_SERVER=http://central:8080
      - DATASET_PATH=/data
      - DATA_SOURCE=parquet
      - PARQUET_FILE=/data/dataset.parquet
      - TARGET_COLUMN=label
      - CUDA_VISIBLE_DEVICES=0
      - BATCH_SIZE=2000
      - MAX_ROWS=50000
      - USE_PARTIAL_FIT=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./client:/app
      - ./data/client2:/data
      - ./platform_utils.py:/platform_utils.py
    depends_on:
      - central
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          memory: 160G
        reservations:
          memory: 96G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # GPU access configuration
    privileged: true
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 8gb

  client3:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    environment:
      - CLIENT_ID=client3
      - CENTRAL_SERVER=http://central:8080
      - DATASET_PATH=/data
      - DATA_SOURCE=parquet
      - PARQUET_FILE=/data/dataset.parquet
      - TARGET_COLUMN=label
      - CUDA_VISIBLE_DEVICES=0
      - BATCH_SIZE=2000
      - MAX_ROWS=50000
      - USE_PARTIAL_FIT=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./client:/app
      - ./data/client3:/data
      - ./platform_utils.py:/platform_utils.py
    depends_on:
      - central
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          memory: 160G
        reservations:
          memory: 96G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # GPU access configuration
    privileged: true
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 8gb

networks:
  fl_network:
    driver: bridge