version: '3'

services:
  central:
    build:
      context: .
      dockerfile: docker/central/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./central_server:/app
      - ./platform_utils.py:/platform_utils.py
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  client1:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    environment:
      - CLIENT_ID=client1
      - CENTRAL_SERVER=http://central:8080
      - DATASET_PATH=/data
      - DATA_SOURCE=parquet
      - PARQUET_FILE=/data/dataset.parquet
      - TARGET_COLUMN=label
      - NVIDIA_VISIBLE_DEVICES=all
      - BATCH_SIZE=500
      - MAX_ROWS=50000
      - USE_PARTIAL_FIT=true
    volumes:
      - ./client:/app
      - ./data/client1:/data
      - ./platform_utils.py:/platform_utils.py
    depends_on:
      - central
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          memory: 40G
        reservations:
          memory: 24G

  client2:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    environment:
      - CLIENT_ID=client2
      - CENTRAL_SERVER=http://central:8080
      - DATASET_PATH=/data
      - DATA_SOURCE=parquet
      - PARQUET_FILE=/data/dataset.parquet
      - TARGET_COLUMN=label
      - NVIDIA_VISIBLE_DEVICES=all
      - BATCH_SIZE=500
      - MAX_ROWS=50000
      - USE_PARTIAL_FIT=true
    volumes:
      - ./client:/app
      - ./data/client2:/data
      - ./platform_utils.py:/platform_utils.py
    depends_on:
      - central
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          memory: 40G
        reservations:
          memory: 24G

  client3:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    environment:
      - CLIENT_ID=client3
      - CENTRAL_SERVER=http://central:8080
      - DATASET_PATH=/data
      - DATA_SOURCE=parquet
      - PARQUET_FILE=/data/dataset.parquet
      - TARGET_COLUMN=label
      - NVIDIA_VISIBLE_DEVICES=all
      - BATCH_SIZE=500
      - MAX_ROWS=50000
      - USE_PARTIAL_FIT=true
    volumes:
      - ./client:/app
      - ./data/client3:/data
      - ./platform_utils.py:/platform_utils.py
    depends_on:
      - central
    networks:
      - fl_network
    deploy:
      resources:
        limits:
          memory: 40G
        reservations:
          memory: 24G

networks:
  fl_network:
    driver: bridge